server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false

alert-api:
  ## Paths to save/read cache list
  out-path: ./app/resources/alerts.list
  in-path: ./app/resources/alerts.list
  ## Time-Zone
  zone: "Europe/Warsaw"
  ## Enable filter out old alerts
  actual-filter: false
##open-api map paths
springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/ui"
