server:
  port: 8888

#logging:
#  file:
#    name: logs/logback.txt

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

alert-api:
  ## Paths to save/read cache list
  out-path: ./app/resources/alerts.list
  in-path: ./app/resources/alerts.list
  ## Time-Zone
  zone: "Europe/Warsaw"
  ## Enable filter out old alerts
  actual-filter: false
##open-api map paths
springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/ui"
